// app/layout.tsx
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import Link from 'next/link'

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900'
})
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900'
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<header>
					<nav className='navbar'>
						<ul className='nav-list'>
							<li className='nav-item'>
								<Link href='/'>Home</Link>
							</li>
							<li className='nav-item'>
								<Link href='/courses'>Courses</Link>
							</li>
							<li className='nav-item'>
								<Link href='/categories'>Categories</Link>
							</li>
							<li className='nav-item'>
								<Link href='/lessons'>Lessons</Link>
							</li>
						</ul>
					</nav>
				</header>
				<main>{children}</main>
				<footer>
					<p>&copy; {new Date().getFullYear()} LMS Platform</p>
				</footer>
			</body>
		</html>
	)
}
